// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rise.Persistence;

#nullable disable

namespace Rise.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BaseUserChat", b =>
                {
                    b.Property<int>("ChatsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ChatsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("BaseUser_Chat", (string)null);
                });

            modelBuilder.Entity("EmergencySupervisor", b =>
                {
                    b.Property<int>("AllowedToResolveId")
                        .HasColumnType("int");

                    b.Property<int>("EmergencyId")
                        .HasColumnType("int");

                    b.HasKey("AllowedToResolveId", "EmergencyId");

                    b.HasIndex("EmergencyId");

                    b.ToTable("Emergcency_Supervisors_AllowedToResolve", (string)null);
                });

            modelBuilder.Entity("EmergencySupervisor1", b =>
                {
                    b.Property<int>("Emergency1Id")
                        .HasColumnType("int");

                    b.Property<int>("HasResolvedId")
                        .HasColumnType("int");

                    b.HasKey("Emergency1Id", "HasResolvedId");

                    b.HasIndex("HasResolvedId");

                    b.ToTable("Emergcency_Supervisors_HasResolved", (string)null);
                });

            modelBuilder.Entity("Event_User_InterestedUsers", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventInterestedUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("IdentityRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("IdentityRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("IdentityUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("IdentityUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("IdentityUserTokens", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Chats.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("ChatType");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Emergencies.Emergency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("MadeByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MadeByUserId");

                    b.ToTable("Emergencies", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Events.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<double>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Messages.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioContentType")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<byte[]>("AudioData")
                        .HasColumnType("longblob");

                    b.Property<double?>("AudioDurationSeconds")
                        .HasColumnType("double");

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Organizations.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Registrations.RegistrationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedSupervisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSupervisorId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("RegistrationRequests", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Users.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("BaseUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Rise.Domain.Users.Connections.UserConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("ToId");

                    b.HasIndex("FromId", "ToId", "IsDeleted");

                    b.ToTable("UserConnections", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Users.Hobbys.UserHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Hobby")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("Hobby")
                        .IsUnique();

                    b.ToTable("Hobbies", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Users.Sentiment.UserSentiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Category")
                        .IsUnique();

                    b.ToTable("Sentiments", (string)null);
                });

            modelBuilder.Entity("Rise.Persistence.Configurations.Users.Hobbies.UserHobbyJoin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "HobbyId");

                    b.HasIndex("HobbyId");

                    b.ToTable("User_Hobby", (string)null);
                });

            modelBuilder.Entity("Rise.Persistence.Configurations.Users.Sentiments.UserSentimentJoin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SentimentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SentimentId");

                    b.HasIndex("SentimentId");

                    b.ToTable("User_Sentiment", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Users.Admin", b =>
                {
                    b.HasBaseType("Rise.Domain.Users.BaseUser");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Users.Supervisor", b =>
                {
                    b.HasBaseType("Rise.Domain.Users.BaseUser");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Supervisors", (string)null);
                });

            modelBuilder.Entity("Rise.Domain.Users.User", b =>
                {
                    b.HasBaseType("Rise.Domain.Users.BaseUser");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BaseUserChat", b =>
                {
                    b.HasOne("Rise.Domain.Chats.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmergencySupervisor", b =>
                {
                    b.HasOne("Rise.Domain.Users.Supervisor", null)
                        .WithMany()
                        .HasForeignKey("AllowedToResolveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Emergencies.Emergency", null)
                        .WithMany()
                        .HasForeignKey("EmergencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmergencySupervisor1", b =>
                {
                    b.HasOne("Rise.Domain.Emergencies.Emergency", null)
                        .WithMany()
                        .HasForeignKey("Emergency1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.Supervisor", null)
                        .WithMany()
                        .HasForeignKey("HasResolvedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Event_User_InterestedUsers", b =>
                {
                    b.HasOne("Rise.Domain.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rise.Domain.Emergencies.Emergency", b =>
                {
                    b.HasOne("Rise.Domain.Chats.Chat", "HappenedInChat")
                        .WithMany("Emergencies")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.BaseUser", "MadeByUser")
                        .WithMany()
                        .HasForeignKey("MadeByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.EmergencyRange", "Range", b1 =>
                        {
                            b1.Property<int>("EmergencyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("EndRangeValue");

                            b1.HasKey("EmergencyId");

                            b1.HasIndex("End");

                            b1.ToTable("Emergencies");

                            b1.WithOwner()
                                .HasForeignKey("EmergencyId");
                        });

                    b.Navigation("HappenedInChat");

                    b.Navigation("MadeByUser");

                    b.Navigation("Range")
                        .IsRequired();
                });

            modelBuilder.Entity("Rise.Domain.Messages.Message", b =>
                {
                    b.HasOne("Rise.Domain.Chats.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.BaseUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.TextMessage", "Text", b1 =>
                        {
                            b1.Property<int>("MessageId")
                                .HasColumnType("int");

                            b1.Property<bool>("IsSuspicious")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("IsSuspicious");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("varchar(2000)")
                                .HasColumnName("Text");

                            b1.HasKey("MessageId");

                            b1.ToTable("Message");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("Chat");

                    b.Navigation("Sender");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("Rise.Domain.Registrations.RegistrationRequest", b =>
                {
                    b.HasOne("Rise.Domain.Users.Supervisor", "AssignedSupervisor")
                        .WithMany()
                        .HasForeignKey("AssignedSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rise.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("RegistrationRequestId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Email");

                            b1.HasKey("RegistrationRequestId");

                            b1.ToTable("RegistrationRequests");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationRequestId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.AvatarUrl", "AvatarUrl", b1 =>
                        {
                            b1.Property<int>("RegistrationRequestId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("AvatarUrl");

                            b1.HasKey("RegistrationRequestId");

                            b1.ToTable("RegistrationRequests");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationRequestId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.BirthDay", "BirthDay", b1 =>
                        {
                            b1.Property<int>("RegistrationRequestId")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("BirthDay");

                            b1.HasKey("RegistrationRequestId");

                            b1.ToTable("RegistrationRequests");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationRequestId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.FirstName", "FirstName", b1 =>
                        {
                            b1.Property<int>("RegistrationRequestId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("FirstName");

                            b1.HasKey("RegistrationRequestId");

                            b1.ToTable("RegistrationRequests");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationRequestId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.LastName", "LastName", b1 =>
                        {
                            b1.Property<int>("RegistrationRequestId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("RegistrationRequestId");

                            b1.ToTable("RegistrationRequests");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationRequestId");
                        });

                    b.OwnsOne("Rise.Domain.Registrations.RegistrationStatus", "Status", b1 =>
                        {
                            b1.Property<int>("RequestId")
                                .HasColumnType("int");

                            b1.Property<int?>("HandledById")
                                .HasColumnType("int")
                                .HasColumnName("HandledById");

                            b1.Property<DateTime?>("HandledDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime(6)")
                                .HasDefaultValue(new DateTime(2025, 12, 3, 10, 36, 54, 652, DateTimeKind.Utc).AddTicks(9522))
                                .HasColumnName("HandledDate");

                            b1.Property<int>("StatusType")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("StatusType");

                            b1.HasKey("RequestId");

                            b1.HasIndex("HandledById");

                            b1.ToTable("RegistrationRequests");

                            b1.HasOne("Rise.Domain.Users.Supervisor", "HandledBy")
                                .WithMany()
                                .HasForeignKey("HandledById");

                            b1.WithOwner("Request")
                                .HasForeignKey("RequestId");

                            b1.OwnsOne("Rise.Domain.Common.ValueObjects.RegistrationNote", "Note", b2 =>
                                {
                                    b2.Property<int>("RegistrationStatusRequestId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("varchar(200)")
                                        .HasColumnName("Note");

                                    b2.HasKey("RegistrationStatusRequestId");

                                    b2.ToTable("RegistrationRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("RegistrationStatusRequestId");
                                });

                            b1.Navigation("HandledBy");

                            b1.Navigation("Note");

                            b1.Navigation("Request");
                        });

                    b.Navigation("AssignedSupervisor");

                    b.Navigation("AvatarUrl")
                        .IsRequired();

                    b.Navigation("BirthDay")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Rise.Domain.Users.BaseUser", b =>
                {
                    b.OwnsOne("Rise.Domain.Common.ValueObjects.Biography", "Biography", b1 =>
                        {
                            b1.Property<int>("BaseUserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("Biography");

                            b1.HasKey("BaseUserId");

                            b1.ToTable("BaseUsers");

                            b1.WithOwner()
                                .HasForeignKey("BaseUserId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.AvatarUrl", "AvatarUrl", b1 =>
                        {
                            b1.Property<int>("BaseUserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("AvatarUrl");

                            b1.HasKey("BaseUserId");

                            b1.ToTable("BaseUsers");

                            b1.WithOwner()
                                .HasForeignKey("BaseUserId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.BirthDay", "BirthDay", b1 =>
                        {
                            b1.Property<int>("BaseUserId")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("BirthDay");

                            b1.HasKey("BaseUserId");

                            b1.ToTable("BaseUsers");

                            b1.WithOwner()
                                .HasForeignKey("BaseUserId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.FirstName", "FirstName", b1 =>
                        {
                            b1.Property<int>("BaseUserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("FirstName");

                            b1.HasKey("BaseUserId");

                            b1.ToTable("BaseUsers");

                            b1.WithOwner()
                                .HasForeignKey("BaseUserId");
                        });

                    b.OwnsOne("Rise.Domain.Common.ValueObjects.LastName", "LastName", b1 =>
                        {
                            b1.Property<int>("BaseUserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("BaseUserId");

                            b1.ToTable("BaseUsers");

                            b1.WithOwner()
                                .HasForeignKey("BaseUserId");
                        });

                    b.OwnsOne("Rise.Domain.Users.Settings.UserSetting", "UserSettings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsDarkMode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("UserSetting", (string)null);

                            b1.WithOwner("User")
                                .HasForeignKey("UserId");

                            b1.OwnsOne("Rise.Domain.Common.ValueObjects.FontSize", "FontSize", b2 =>
                                {
                                    b2.Property<int>("UserSettingId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Value")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasDefaultValue(12)
                                        .HasColumnName("FontSize");

                                    b2.HasKey("UserSettingId");

                                    b2.ToTable("UserSetting");

                                    b2.WithOwner()
                                        .HasForeignKey("UserSettingId");
                                });

                            b1.OwnsMany("Rise.Domain.Users.Settings.UserSettingChatTextLineSuggestion", "ChatTextLineSuggestions", b2 =>
                                {
                                    b2.Property<int>("UserSettingsId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("Rank")
                                        .HasColumnType("int");

                                    b2.HasKey("UserSettingsId", "Id");

                                    b2.ToTable("UserSettingChatTextLineSuggestions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("UserSettingsId");

                                    b2.OwnsOne("Rise.Domain.Common.ValueObjects.DefaultSentence", "Sentence", b3 =>
                                        {
                                            b3.Property<int>("UserSettingChatTextLineSuggestionUserSettingsId")
                                                .HasColumnType("int");

                                            b3.Property<int>("UserSettingChatTextLineSuggestionId")
                                                .HasColumnType("int");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(150)
                                                .HasColumnType("varchar(150)")
                                                .HasColumnName("TextSuggestion");

                                            b3.HasKey("UserSettingChatTextLineSuggestionUserSettingsId", "UserSettingChatTextLineSuggestionId");

                                            b3.ToTable("UserSettingChatTextLineSuggestions");

                                            b3.WithOwner()
                                                .HasForeignKey("UserSettingChatTextLineSuggestionUserSettingsId", "UserSettingChatTextLineSuggestionId");
                                        });

                                    b2.Navigation("Sentence")
                                        .IsRequired();
                                });

                            b1.Navigation("ChatTextLineSuggestions");

                            b1.Navigation("FontSize")
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("AvatarUrl")
                        .IsRequired();

                    b.Navigation("Biography")
                        .IsRequired();

                    b.Navigation("BirthDay")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("UserSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Rise.Domain.Users.Connections.UserConnection", b =>
                {
                    b.HasOne("Rise.Domain.Users.User", "From")
                        .WithMany("Connections")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.User", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Rise.Persistence.Configurations.Users.Hobbies.UserHobbyJoin", b =>
                {
                    b.HasOne("Rise.Domain.Users.Hobbys.UserHobby", "Hobby")
                        .WithMany()
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rise.Persistence.Configurations.Users.Sentiments.UserSentimentJoin", b =>
                {
                    b.HasOne("Rise.Domain.Users.Sentiment.UserSentiment", "Sentiment")
                        .WithMany()
                        .HasForeignKey("SentimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentiment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rise.Domain.Users.Admin", b =>
                {
                    b.HasOne("Rise.Domain.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("Rise.Domain.Users.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rise.Domain.Users.Supervisor", b =>
                {
                    b.HasOne("Rise.Domain.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("Rise.Domain.Users.Supervisor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Organizations.Organization", "Organization")
                        .WithMany("Workers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Rise.Domain.Users.User", b =>
                {
                    b.HasOne("Rise.Domain.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("Rise.Domain.Users.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Organizations.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rise.Domain.Users.Supervisor", "Supervisor")
                        .WithMany("Users")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Rise.Domain.Chats.Chat", b =>
                {
                    b.Navigation("Emergencies");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Rise.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("Rise.Domain.Users.Supervisor", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Rise.Domain.Users.User", b =>
                {
                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
