@Rise.Server_HostAddress = http://localhost:5109

### Authenticate with a test user (stores auth cookie in the HTTP client)
POST {{Rise.Server_HostAddress}}/api/identity/accounts/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "A1b2C3!"
}

### Retrieve the authenticated user's friends, requests and suggestions
GET {{Rise.Server_HostAddress}}/api/friends

### Add user with ID 2 as a friend
POST {{Rise.Server_HostAddress}}/api/friends/2
Content-Type: application/json

{
  "friendId": 2
}

### Remove an existing friend with ID 2
DELETE {{Rise.Server_HostAddress}}/api/friends/2
Content-Type: application/json

{
  "friendId": 2
}
