using System.Text.RegularExpressions;

namespace Rise.Services
{
    public class WordFilter
    {
        private readonly HashSet<string> _blacklistedWords = new(StringComparer.OrdinalIgnoreCase);
        private readonly Regex _blacklistRegex;

        public WordFilter()
        {
            // check if certain words can be removed
            // also regex for l33tstyle writing
            //  example: sh1t
            _blacklistedWords =
            [
                "dom", "stom", "vloekwoord", "aardappels afgieten",
                "achter het raam zitten", "afberen",
                "aflebberen",
                "afrossen",
                "afrukken",
                "aftrekken",
                "afwerkplaats", "afzeiken", "afzuigen",
                "een halve man en een paardekop",
                "anita",
                "asbak",
                "aso",
                "bagger schijten",
                "balen",
                "bedonderen",
                "befborstel",
                "beffen",
                "bekken",
                "belazeren",
                "besodemieterd zijn",
                "besodemieteren",
                "beurt",
                "boemelen",
                "boerelul",
                "boerenpummel",
                "bokkelul",
                "botergeil",
                "broekhoesten",
                "brugpieper",
                "buffelen",
                "buiten de pot piesen",
                "da's kloten van de bok",
                "de ballen",
                "de hoer spelen",
                "de hond uitlaten",
                "de koffer induiken",
                "del",
                "de pijp uitgaan",
                "dombo",
                "draaikont",
                "driehoog achter wonen",
                "drol",
                "drooggeiler",
                "droogkloot",
                "een beurt geven",
                "een nummertje maken",
                "een wip maken",
                "eikel",
                "engerd",
                "flamoes",
                "flikken",
                "flikker",
                "gadverdamme",
                "galbak",
                "gat",
                "gedoogzone",
                "geilneef",
                "gesodemieter",
                "godverdomme",
                "graftak",
                "gras maaien",
                "gratenkut",
                "greppeldel",
                "griet",
                "hoempert",
                "hoer",
                "hoerenbuurt",
                "hoerenloper",
                "hoerig",
                "hol",
                "hufter",
                "huisdealer",
                "johny",
                "kanen",
                "kettingzeug",
                "klaarkomen",
                "klerebeer",
                "klojo",
                "klooien",
                "klootjesvolk",
                "klootoog",
                "klootzak",
                "kloten",
                "knor",
                "kont",
                "kontneuken",
                "krentekakker",
                "kut",
                "kuttelikkertje",
                "kwakkie",
                "liefdesgrot",
                "lul",
                "lul-de-behanger",
                "lulhannes",
                "lummel",
                "mafketel",
                "matennaaier",
                "matje",
                "mof",
                "muts",
                "naaien",
                "naakt",
                "neuken",
                "neukstier",
                "nicht",
                "oetlul",
                "opgeilen",
                "opkankeren",
                "oprotten",
                "opsodemieteren",
                "op z'n hondjes",
                "op z'n sodemieter geven",
                "opzouten",
                "ouwehoer",
                "ouwehoeren",
                "ouwe rukker",
                "paal",
                "paardelul",
                "palen",
                "penoze",
                "piesen",
                "pijpbekkieg",
                "pijpen",
                "pik",
                "pleurislaaier",
                "poep",
                "poepen",
                "poot",
                "portiekslet",
                "pot",
                "potverdorie",
                "publiciteitsgeil",
                "raaskallen",
                "reet",
                "reetridder",
                "reet trappen, voor zijn",
                "remsporen",
                "reutelen",
                "rothoer",
                "rotzak",
                "rukhond",
                "rukken",
                "schatje",
                "schijt",
                "schijten",
                "schoft",
                "schuinsmarcheerder",
                "shit",
                "slempen",
                "slet",
                "sletterig",
                "slik mijn zaad",
                "snol",
                "spuiten",
                "standje",
                "standje-69",
                "stoephoer",
                "stootje",
                "stront",
                "sufferd",
                "tapijtnek",
                "teef",
                "temeier",
                "teringlijer",
                "toeter",
                "tongzoeng",
                "triootjeg",
                "trottoir prostituée",
                "trottoirteef",
                "vergallen",
                "verkloten",
                "verneuken",
                "viespeuk",
                "vingeren",
                "vleesroos",
                "voor jan lul",
                "voor jan-met-de-korte-achternaam",
                "watje",
                "welzijnsmafia",
                "wijf",
                "wippen",
                "wuftje",
                "zaadje",
                "zakkenwasser",
                "zeiken",
                "zeiker",
                "zuigen",
                "zuiplap",
                "abbo", "abo", "abortus", "misbruik", "verslaafde", "verslaafden", "volwassene", "afrikaans",
                "alla", "allah", "alligatorbait", "amateur", "Amerikaans", "anaal", "analannie", "analsex",
                "angie", "boos", "anus", "arabisch", "arabiërs", "areola", "argie", "opgewonden", "kont", "kontgat",
                "kont", "moordenaar", "moordenaar", "moord", "aanval", "kontbagger", "kontblazer",
                "kontclown", "kontjongen", "konten", "kontneuken", "kontneuker", "kont", "kontgat", "kontgat",
                "kontjockey", "kontlikken", "kontlikken", "kontlikker", "kontliefhebber", "kontman",
                "kontapijt", "kontsnuiter", "kontsnuiter", "kontverpakker", "aspireren", "kontpuppies", "kontranger",
                "konthoer", "kontswipe", "atletenvoet", "aanval", "Australiër", "babe", "baby's", "achterdeur",
                "backdoorman", "backseat", "badfuck", "balllicker", "balls", "ballsack", "banging", "baptist",
                "barelylegal", "barf", "barface", "barfface", "bast", "bastard", "bazongas", "bazooms", "beaner",
                "beestachtigheid", "beestachtig", "beestachtigheid", "beatoff", "beat-off", "beatyourmeat", "bever",
                "beestachtig", "beestachtigheid", "bi", "biatch", 
                 "aambeienlikker", "aapmens", "aardappel", "aarstulp", "achterlader", "adder", "addergebroed",
                "apenjong", "apenkont", "appelflap", "autist", "babi", "babok", "badgast", "baggerduiker",
                "bal", "bandiet", "bangerd", "barslet", "bedrijfspoedel", "beheime", "belhamel", "bermslet",
                "biljartbal", "bitch", "blaag", "bleekscheet", "bliksemstraal", "bloedlijer", "boef", "boeler",
                "boer", "boerenheikneuter", "boerenhufter", "boerenkaffer", "boerenkarhengst", "boerenkinkel",
                "boerenpummel", "boerin", "bokkenlul", "bokkenrijder", "booswicht", "bosneuker", "botterik",
                "bouwdoos", "braadvarken", "breezerslet", "brilaap", "brillenjood", "brilsmurf", "broodaap",
                "bruinwerker", "bruut", "bulderbast", "charlatan", "choco", "chocoladehoer", "chocoladesnol",
                "cijferneuker", "coronalijer", "covidioot", "cretin", "debiel", "del", "deuggleuf", "deugkneus",
                "diepduiker", "dirkdoos", "dombo", "doos", "dreuzel", "droplul", "druifluis", "druiloor",
                "dwaas", "ectoplasma", "eend", "eendenkont", "egghead", "eikel", "ellendeling", "engerling",
                "erwtenteller", "etter", "etterbuil", "ezel", "fielt", "flapdrol", "fleer", "flessentrekker",
                "flikker", "foefkop", "fransoos", "galgenbrok", "gangster", "gannef", "geboefte", "geit",
                "geitenbreier", "geitenneuker", "gemenerik", "gespuis", "geteisem", "gladakker", "gleuf",
                "gluiper", "gluiperd", "gluipsnor", "gortenteller", "gratenbaal", "greppeldel", "grobbejanus",
                "haaibaai", "halvezool", "hapsnurker", "harpij", "heaumeau", "heihaas", "heikneuter",
                "heks", "hersenlijer", "hielenlikker", "hockeytrut", "hockeytut", "hoer", "hoerenjager",
                "hoerenjong", "hoerenkind", "hoerenzoon", "homo", "hond", "hondenlul", "hondenneuker",
                "hork", "hufter", "huichelaar", "huppelkut", "huzarenhoop", "janhagel", "jeannette",
                "kaas", "kaashoer", "kaaskop", "kaffer", "kakhuis", "kakkerlak", "kakmadam", "kakmaker",
                "kamelenneuker", "kamerolifant", "kankerhoer", "kankerhond", "kankerlijder", "kankerlijer",
                "kankernicht", "kankerslet", "kantoorpik", "kapsoneslijer", "karhengst", "karonje", "karpatenkop",
                "kees", "keilef", "kelerelijer", "keutelkut", "kinkel", "kip", "kippenneuker", "klafte",
                "klapkut", "klapluis", "klaplul", "klapperaap", "klere", "klier", "kloefkapper", "klojo",
                "klooi", "kloothannes", "kloothommel", "klootviool", "klootzak", "klungel", "kluns",
                "knijpkont", "knurft", "koekwaus", "koekwous", "koeskoesvreter", "koffieboon", "kokosmakroon",
                "kontkruiper", "kontlikker", "kontneuker", "kreng", "kriel", "krielkip", "krijslijster",
                "kroeskop",
    
                //english curse
                
                "abbo", "abo", "abortion", "abuse", "addict", "addicts", "adult", "africa", "african",
                "alla", "allah", "alligatorbait", "amateur", "american", "anal", "analannie", "analsex",
                "angie", "angry", "anus", "arab", "arabs", "areola", "argie", "aroused", "arse", "arsehole",
                "asian", "ass", "assassin", "assassinate", "assassination", "assault", "assbagger", "assblaster",
                "assclown", "asscowboy", "asses", "assfuck", "assfucker", "asshat", "asshole", "assholes", "asshore",
                "assjockey", "asskiss", "asskisser", "assklown", "asslick", "asslicker", "asslover", "assman",
                "assmonkey", "assmunch", "assmuncher", "asspacker", "asspirate", "asspuppies", "assranger",
                "asswhore", "asswipe", "athletesfoot", "attack", "australian", "babe", "babies", "backdoor",
                "backdoorman", "backseat", "badfuck", "balllicker", "balls", "ballsack", "banging", "baptist",
                "barelylegal", "barf", "barface", "barfface", "bast", "bastard", "bazongas", "bazooms", "beaner",
                "beast", "beastality", "beastial", "beastiality", "beatoff", "beat-off", "beatyourmeat", "beaver",
                "bestial", "bestiality", "bi", "biatch", "bible", "bicurious", "bigass", "bigbastard", "bigbutt",
                "bigger", "bisexual", "bi-sexual", "bitch", "bitcher", "bitches", "bitchez", "bitchin", "bitching",
                "bitchslap", "bitchy", "biteme", "black", "blackman", "blackout", "blacks", "blind", "blow", "blowjob",
                "bogan", "bohunk", "bollock", "bomb", "bombers", "bombing", "bombs", "bondage", "boner", "bong",
                "boob", "boobies", "boobs", "booby", "booty", "bootycall", "bra", "breast", "brothel", "bugger",
                "buggered", "bullshit", "bumfuck", "bunghole", "butt", "buttfuck", "butthead", "buttplug",
                "byatch", "cameljockey", "carpetmuncher", "chink", "choad", "christ", "christian", "clit",
                "clitoris", "cock", "cockhead", "cocklicker", "cocklover", "cockrider", "cocksmoker", "cocksucker",
                "cocktail", "cocktease", "coon", "copulate", "cornhole", "crap", "crapper", "cum", "cumming",
                "cumshot", "cunnilingus", "cunt", "cuntsucker", "cybersex", "damn", "demon", "devil", "dick",
                "dickhead", "dildo", "dipshit", "doggystyle", "dong", "dope", "dragqueen", "drunk", "dumbass",
                "dyke", "eatme", "ejaculate", "erection", "escort", "ethnic", "fag", "faggot", "fart", "fatass",
                "felatio", "fetish", "fingerfuck", "fister", "fistfuck", "flange", "footfuck", "foreskin", "forni",
                "fornicate", "foursome", "fuck", "fucker", "fucking", "fuckoff", "fudgepacker", "fuk", "gangbang",
                "gay", "gaysex", "genital", "givehead", "glazeddonut", "god", "goddamn", "goldenshower", "gook",
                "handjob", "hardon", "headfuck", "hell", "herpes", "hitler", "hiv", "hoes", "hole", "homo",
                "homosexual", "honky", "hooker", "hooters", "horny", "hotpussy", "hump", "idiot", "incest",
                "intercourse", "jackass", "jackoff", "jerkoff", "jesus", "jew", "jizz", "joint", "juggs", "jugs",
                "kike", "kill", "killer", "killing", "kink", "kinky", "knob", "knobhead", "koon", "krap", "kum",
                "kummer", "kumming", "kunilingus", "kunt", "labia", "lapdance", "lesbian", "lezbo", "lickme",
                "limpdick", "lolita", "loser", "lust", "mafia", "marijuana", "masturbate", "meatbeatter",
                "meth", "milf", "molest", "molester", "moneyshot", "motherfucker", "muff", "muffdive",
                "muffdiver", "murder", "muslim", "naked", "nasty", "nazi", "negro", "nigga", "nigger",
                "nipple", "nookie", "nude", "nudity", "oral", "orgasm", "orgy", "paki", "panties", "pecker",
                "pee", "penis", "pimp", "piss", "pissoff", "playboy", "poontang", "porn", "porno", "pussy",
                "queef", "queer", "quickie", "rape", "rapist", "rectum", "redneck", "rimjob", "rimming",
                "sadist", "satan", "scat", "schlong", "screw", "scrotum", "scum", "semen", "sex", "sexual",
                "sexy", "shag", "shit", "shitface", "shithead", "shithole", "shitter", "shitty", "skank",
                "slut", "sluts", "slutty", "smack", "snatch", "sodomize", "spank", "sperm", "spic", "spunk",
                "suck", "suckdick", "sucker", "suicide", "swallow", "tang", "tampon", "testicle", "threesome",
                "tit", "tits", "titties", "titty", "tosser", "tramp", "tranny", "transsexual", "twat",
                "upskirt", "urinate", "urine", "vagina", "vibrator", "virgin", "vulva", "wank", "wanker",
                "whore", "whorehouse", "wtf"
            ];

            var pattern = @"\b(" + string.Join("|", _blacklistedWords.Select(Regex.Escape)) + @")\b";
            _blacklistRegex = new Regex(pattern, RegexOptions.IgnoreCase | RegexOptions.Compiled);
        }

        public string Censor(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
                return string.Empty; //incase the user just spams alot of whitespaces

            return _blacklistRegex.Replace(input, m => new string('#', m.Value.Length));
        }
    }
}